# permissions for end users to edit bgdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bgdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bluegreen-deployment
    app.kubernetes.io/part-of: bluegreen-deployment
    app.kubernetes.io/managed-by: kustomize
  name: bgdeployment-editor-role
rules:
- apiGroups:
  - bgdeployment.example.com
  resources:
  - bgdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bgdeployment.example.com
  resources:
  - bgdeployments/status
  verbs:
  - get
